### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by robertnicjoo** [skrausler/capacitor-contacts#1]
How to use this plugin? would you mind share some info in readme file please?

does it solve cordova contacts issue on ionic apps?

**Comment by skrausler** [comment]
Works only on android atm. i updated the readme with code examples. hope that helps

**Comment by robertnicjoo** [comment]
Thank you, may i ask what do you mean by `android atm`?

**Comment by skrausler** [comment]
it only works on android at the moment - not on ios

**Comment by robertnicjoo** [comment]
well that's what i need 😄  thank you.
